spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BajajTraining?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
